import { APP_CONFIG } from '@/config/env'

export const SEED_DATA = {
  cohort: {
    name: 'Spring 2025 Cohort',
    interviewGoal: APP_CONFIG.interviewGoal,
    startDate: '2025-01-15',
    endDate: '2025-05-30',
  },

  teams: [
    {
      id: 1,
      name: 'BioSync',
      members: ['Alice Chen', 'Marcus Webb'],
      hypothesis: 'Hospital procurement managers need faster IV supply reordering to prevent stockouts.',
      segment: 'Healthcare Supply Chain',
    },
    {
      id: 2,
      name: 'AgroLink',
      members: ['Sara Patel', 'James Kim'],
      hypothesis: 'Small farms need real-time soil data to reduce fertilizer waste by 30%.',
      segment: 'AgTech / Small Farm',
    },
    {
      id: 3,
      name: 'EduFlow',
      members: ['Priya Nair', 'Tomás Reyes'],
      hypothesis: 'K-12 teachers need automated lesson gap analysis to reduce prep time.',
      segment: 'EdTech / K-12',
    },
  ],

  interviews: [
    {
      id: 'iv-001',
      teamId: 1,
      contact: 'Dr. Patricia Moore',
      role: 'Procurement Director',
      org: 'Mass General Hospital',
      date: '2025-04-10',
      status: 'analyzed',
      notes: 'Confirmed pain around reorder delays. Mentioned 3 competing tools but all have poor EHR integration. Budget authority up to $50k/yr.',
      insights: 'Strong pain signal on reorder delays. Budget confirmed. EHR integration is the key differentiator.',
      hypothesisValidated: true,
      createdAt: '2025-04-10T14:00:00Z',
    },
    {
      id: 'iv-002',
      teamId: 1,
      contact: 'Bob Nguyen',
      role: 'Supply Chain Manager',
      org: 'UCSF Health',
      date: '2025-04-14',
      status: 'pending',
      notes: '',
      insights: '',
      hypothesisValidated: null,
      createdAt: '2025-04-14T10:00:00Z',
    },
    {
      id: 'iv-003',
      teamId: 2,
      contact: 'Helen Marsh',
      role: 'Farm Owner',
      org: 'Marsh Organics',
      date: '2025-04-08',
      status: 'analyzed',
      notes: 'Strong pain signal. Currently uses paper logs. Budget concern — max $200/mo. Open to co-design.',
      insights: 'Validated pain. Budget constraint is real. Paper-to-digital transition is the wedge.',
      hypothesisValidated: true,
      createdAt: '2025-04-08T09:00:00Z',
    },
    {
      id: 'iv-004',
      teamId: 2,
      contact: 'Kevin Diaz',
      role: 'County Agronomist',
      org: 'County Extension Office',
      date: '2025-04-12',
      status: 'analyzed',
      notes: 'Influencer, not buyer. Referral to 4 farm owners. Data standardization is concern.',
      insights: 'Good referral source. Not a buyer. Confirms problem exists across region.',
      hypothesisValidated: false,
      createdAt: '2025-04-12T11:00:00Z',
    },
    {
      id: 'iv-005',
      teamId: 3,
      contact: 'Maria Lopez',
      role: '6th Grade Teacher',
      org: 'Jefferson Middle School',
      date: '2025-04-15',
      status: 'pending',
      notes: '',
      insights: '',
      hypothesisValidated: null,
      createdAt: '2025-04-15T15:00:00Z',
    },
  ],

  courses: [
    {
      id: 'c-01',
      title: 'Customer Discovery Fundamentals',
      description: 'Core icompass methodology and lean startup foundations.',
      modules: [
        'Intro to icompass & NSF requirements',
        'The Lean Canvas framework',
        'Interview basics & mindset',
        'Hypothesis framework',
      ],
      completedBy: { 1: [0, 1], 2: [0, 1, 2], 3: [] },
    },
    {
      id: 'c-02',
      title: 'Interview Execution',
      description: 'How to run effective discovery interviews.',
      modules: [
        'Crafting open-ended questions',
        'Active listening techniques',
        'Signal vs. noise in responses',
        'Recognizing pivot signals',
      ],
      completedBy: { 1: [], 2: [0], 3: [] },
    },
    {
      id: 'c-03',
      title: 'Post-Interview Analysis',
      description: 'Turning raw interview data into actionable insights.',
      modules: [
        'Tagging and categorizing insights',
        'Pattern detection across interviews',
        'Updating hypotheses with evidence',
        'Presenting findings to NSF',
      ],
      completedBy: { 1: [], 2: [], 3: [] },
    },
  ],

  notifications: [
    {
      id: 'n-001',
      text: 'BioSync logged interview #8 — approaching their 15-interview goal',
      time: '2h ago',
      read: false,
      type: 'progress',
    },
    {
      id: 'n-002',
      text: 'EduFlow has only 3 interviews — follow-up recommended',
      time: '1d ago',
      read: false,
      type: 'alert',
    },
    {
      id: 'n-003',
      text: 'New course module published: Recognizing pivot signals',
      time: '2d ago',
      read: true,
      type: 'content',
    },
  ],
}
